spring.application.name=todo-api

# H2 Database
spring.datasource.url=jdbc:h2:mem:todo_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (acess\u00edvel em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configura\u00e7\u00f5es opcionais
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

jwt.secret=FzqfmGcII45eFIbi5BPBHWSoYEikydXcu9xsp4v/gYyNC+QSMJeo9p9yoPCsDHvzdbyFWTFFBR+fjMsJ2VTteWWfKKl7thUos0JQBtEgR96vHiETCsbBGnoGq2nfGv6a/mURs+EIH6zHiqvabfYkZcV2Uxs+wG0PbaHmghxQj03b6MWE3KibSWdxOUlIPObdGDQD3g08sIDCCM8PY46OUs8pXoK7ysJj6pNiT3+INNK42zHwh87GBDjlx2vgqLkMZ8StcP2sPvr4WOgeBLypFc2wjObY9UPVjWvT39uNran9DOm743tlNa15Xkia7AqIaZ113WG7OvvruJPO86Pprw==
jwt.expiration=900000

logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG